import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import { Header } from "./component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assesment FE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen mx-auto flex-col items-center justify-between p-4 bg-gray-300">
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
